import = ["/home/michev/.alacritty-colorscheme/themes/gruvbox_dark"]

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
# gtk_theme_variant = "dark"
opacity = 0.8
