[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8

[general]
import = ["/home/michev/.alacritty-colorscheme/themes/gruvbox_dark"]
